### ISSUE TITLE
Currency symbol assumption is wrong

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri#149]
As reported in http://stackoverflow.com/questions/40244526/jsr-354-monetaryamountformat-not-working-two-way-for-other-currency-symbols-than?rq=1
the assumption of "$" has to be "USD" in
https://github.com/JavaMoney/jsr354-ri/blob/master/moneta-core/src/main/java/org/javamoney/moneta/internal/format/CurrencyToken.java
is wrong and a bug.
There are at least 3 other countries (Australia, Canada, New Zealand) using the exact same "$" symbol for totally different currencies like "AUD", etc. Not to mention other cases like "HK$" which you may also find abbreviated. see https://coderanch.com/t/463940/java/show-countries-currency-symbols

**Comment by keilw** [comment]
Actually this is very much a **showstopper**, too. As getting the wrong currency (e.g. `USD` instead of `CAD`) is worse than getting none at all.

**Comment by atsticks** [comment]
Will throw an exception, fixed in both RI and RI-BP.
