### ISSUE TITLE
Make ConvertNumberValue public

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri#152]
Migrated from https://java.net/jira/browse/JAVAMONEY-155

**Comment by Koziolek** [comment]
Hi!

Have you got original description. java.net were closed 28th aprli 20017, and link points to void :)

**Comment by keilw** [comment]
Only in a download archive. We're making that available on Bintray soon.

**Comment by atsticks** [comment]
What are the things you cant do with the current API? I dont see any reasons as of now to make this enum public. It is a purely internal helper class not intended to be any kind of public API.
