### ISSUE TITLE
Provide a way to change the configuration source

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri#153]
Migrated from https://java.net/jira/browse/JAVAMONEY-161

Consider using Tamaya for Moneta configuration.

**Comment by keilw** [comment]
We'll probably defer that till Tamaya graduates from Apache Incubator.

**Comment by keilw** [comment]
There is still no clear direction for a configuration standard, either here (JSR 382 is inactive) or elsewhere, e.g. Jakarta EE. Until that is resolved, we keep this issue on hold.

**Comment by atsticks** [comment]
Added a simple SPI class that can be register with the Money API Bootstrap ServiceLoader. This allows to use any configuration source, including Spring and others to be registered as a config provider.

```
public interface MonetaryConfigProvider {

    /**
     * Simple methoid to get a property.
     * @param key the key, not null.
     * @return the value, or null.
     */
    default String getProperty(String key){
        return getProperties().get(key);
    }

    /**
     * Get all currently known properties.
     * @return the properties, never null.
     */
    Map<String, String> getProperties();
}
```
