### ISSUE TITLE
Searching currencies using currency numeric code does not select any currencies

### ISSUE THREAD

**Issue by atsticks** [JavaMoney/jsr354-ri#154]
It looks that querying currencies using a CurrencyQuery, where only one numeric code is passed as parameter, does effectively return the full list of currencies. In case of a single currency value access a MonetaryException is thrown , since the result is considered ambigous!

**Comment by keilw** [comment]
@atsticks would you consider this a `showstopper`?

**Comment by atsticks** [comment]
we should fix it imo...

Am 06.07.2017 23:09 schrieb "Werner Keil" <notifications@github.com>:

**Comment by keilw** [comment]
Ok, set label accordingly. Like with Jigsaw it's better to take a bit more time and fix important issues;-) 
Is this only an issue in Moneta?

**Comment by atsticks** [comment]
Fixed.
