### ISSUE TITLE
NPE accessing a default MonetaryAmountFormat if no Locale is set

### ISSUE THREAD

**Issue by atsticks** [JavaMoney/jsr354-ri#156]
Accessing a format results in a NPE, when no Locale is present on the `MonetaryAmountFormatQuery` passed.
**Expected behaviour:**
- Use `Locale.getDefault()` or
- throw a `MonetaryException` on `MonetaryFormatQuery.build()`.

**Comment by otaviojava** [comment]
Hey @atsticks The `MonetaryFormatQuery` does not exist in the package. 
Could you give me more details about the problem?
