### ISSUE TITLE
Question regarding creation of MonetaryAmount

### ISSUE THREAD

**Issue by ralfhecktor** [JavaMoney/jsr354-ri#162]
Hello,

I am new to JSR354 and currently trying to integrate it in a project I am working on. For that I would like to have all newly created MonetaryAmount instances directly shortened to two decimal places. 

I am creating a MonetaryContext as follows:

``` java
MonetaryContext mc = MonetaryContextBuilder.of().setMaxScale(2).setPrecision(64).set(RoundingMode.HALF_DOWN).build()
```

And afterwards my MonetaryAmount as follows:

``` java
Monetary.getDefaultAmountFactory().setContext(mc).setNumber(999.999).setCurrency("EUR").create()
```

What I expect is, that the created and assigned monetary context is used and the created Money object has a number value of "999.99" but instead it still has "999.999". I think it might be, because the piece of code bellow (AbstractAmountBuilder), does not realy do, what it should do and the JavaDoc says, namly taking the MonetaryContext into consideration while creating the BigDecimal. Am I correct or am I missing something? 

``` java
    /**
     * Creates a new instance of {@link Monetary}, using the default {@link MonetaryContext}.
     *
     * @param number numeric value.
     * @return a {@code Money} combining the numeric value and currency unit.
     * @throws ArithmeticException      If the number exceeds the capabilities of the default {@link MonetaryContext}
     *                                  used.
     * @throws UnknownCurrencyException if the currency code can not be resolved to {@link CurrencyUnit}.
     */
    @Override
    public MonetaryAmountFactory<T> setNumber(double number) {
        this.number = new BigDecimal(String.valueOf(number));
        return this;
    }
```

**Comment by ralfhecktor** [comment]
Anybody willing to give a brief answer on that question please?

**Comment by keilw** [comment]
Several are busy with the online/query issue discovered with Exchange Rate providers like IMF, so please excuse a slight delay. I'll look into it. 

`using the default {@link MonetaryContext}.` states, that the default context is used, not a the `MonetaryContext` one may have set here.  The created Money should take everything into consideration. 
Do you have a JUnit test to show this behavior? It would be handy for analysis.

**Comment by keilw** [comment]
I added 

https://github.com/JavaMoney/jsr354-ri/blob/master/moneta-core/src/main/java/org/javamoney/moneta/spi/MoneyUtils.java

**Comment by ralfhecktor** [comment]
Thanks for your response. I will have a look into what you have done and add some suggestions.

**Comment by atsticks** [comment]
I basically agree that the behaviour is weired. **Especially when setting a constraining MonetaryContext on a type, which is capable of supporting it (Money/MoneyAmountFactory in our case), then I would expect rounting to happen in this case.** Though in most cases we recommend to not constrain the amount's value to simplify later formatting tasks. Especially then you also do calculations with the amount at a later stage in your code rounding to early may introduce significant (hard to find) rounding errors.

**Comment by atsticks** [comment]
Actually scale is not taken into account. Fixed on master.

**Note:** For the example to work `RoundingMode.FLOOR` must be used, because without the value will be rounded to `1000.00`. This is also reflected in an additional test.

**Comment by atsticks** [comment]
Fixed on master, both JDK8 and backport.
