### ISSUE TITLE
MoneyAmountBuilder.DEFAULT_CONTEXT does not set precision

### ISSUE THREAD

**Issue by hdohlmann** [JavaMoney/jsr354-ri#171]
Steps to reproduce:
```java
MonetaryAmount a = Monetary.getDefaultAmountFactory().setNumber(100).setCurrency("DKK").create();
a.divide(BigDecimal.valueOf(3));
```
This throws `ArithmeticExpression`.

The error can be spotted in `MoneyAmountBuilder`:
```java
    static final MonetaryContext DEFAULT_CONTEXT =
           MonetaryContextBuilder.of(Money.class).set(64).setMaxScale(63).set(RoundingMode.HALF_EVEN).build();
```
Note the use of `.set(64)`. This should have been `.setPrecision(64)`.

BTW: Why doesn't the `MoneyAmountBuilder` use the `Money.DEFAULT_MONETARY_CONTEXT`?

**Comment by atsticks** [comment]
Here is the exact code in RI (Java 8), must also check for issue in BP...
```
public class MoneyAmountFactory extends AbstractAmountFactory<Money> {
    static final MonetaryContext DEFAULT_CONTEXT = MonetaryContextBuilder.of(Money.class).set(64).setMaxScale(63).set(RoundingMode.HALF_EVEN).build();
```

**Comment by atsticks** [comment]
The MonetaryContext hasn't been propagated on arithmetic operations, which is definitly a bug. Fixed.
Scale was never considered, though set. Fixed.
Precision was never considered. Fixed.
