### ISSUE TITLE
DefaultLoaderService::getData always throws because of a missing return statement

### ISSUE THREAD

**Issue by okarm** [JavaMoney/jsr354-ri#174]
https://github.com/JavaMoney/jsr354-ri/blob/cc7860fe6fdd298911a39505ca179995c7e1bfa4/moneta-core/src/main/java/org/javamoney/moneta/internal/loader/DefaultLoaderService.java#L257

The result of `getDataStream()` is not returned.

**Comment by Koziolek** [comment]
Hi!

I added return statement to make method return not only throw. 

Have nice day.
