### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J

### ISSUE THREAD

**Issue by funmler** [JavaMoney/jsr354-ri#189]
A Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J is thrown 
using moneta-core-1.2.1 with jdk1.8.0_144

Full stack trace
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J
	at org.javamoney.moneta.FastMoney.negate(FastMoney.java:394)
	at Main.main(Main.java:7)

Source file 
```java
import org.javamoney.moneta.FastMoney;


public class Main {

    public static void main(String[] args)    {
        FastMoney m = FastMoney.of(400, "CAD");
        m.negate();
    }
}
```

**Comment by keilw** [comment]
@marschall Can this be closed because of the merged PRs?

**Comment by marschall** [comment]
Yes this is closed by the PRs.
