### ISSUE TITLE
Make Money::with less restritive to support interop with others implementations

### ISSUE THREAD

**Issue by DiegoCoronel** [JavaMoney/jsr354-ri#190]
I had a situation where I needed to implement my own `MonetaryAmount` (decorated Money) and now Im not able to integrate my code smooth with `Money::with` because theres a forced cast to Money. Is it possible to relax this and return a `MonetaryAmount` ?

```java
    @Override
    public Money with(MonetaryOperator operator) { // <-- Can you return MonetaryAmount ?
        Objects.requireNonNull(operator);
        try {
            return Money.class.cast(operator.apply(this)); // <-- Can you relax this code ?
        } catch (MonetaryException e) {
            throw e;
        } catch (Exception e) {
            throw new MonetaryException("Operator failed: " + operator, e);
        }
    }
```

**Comment by marschall** [comment]
For that the return type would have to change, wouldn't it?

**Comment by keilw** [comment]
I think because `Money` implements `MonetaryAmount` it should work.

**Comment by marschall** [comment]
What I mean is currently the method signature is:
```java
public Money with(MonetaryOperator operator)
```
we would have to change that to 

```java
public MonetaryAmount with(MonetaryOperator operator)
```

Which beaks both source and binary compatibility.

In additon when I look at the specification of [MonetaryAmount#with(MonetaryOperator)](http://javamoney.github.io/apidocs/javax/money/MonetaryAmount.html#with-javax.money.MonetaryOperator-) it states that

> Returns an operated object of the same type as this object with the operation made. Hereby returning an instannce of the same type is very important to prevent uncontrolled mixup of implementations. Switching between implementations is still easily possible, e.g. by using according MonetaryAmountFactory instances

So I believe the current behavior is what the spec requires and implementing this issue would make us break the spec.

**Comment by marschall** [comment]
The specification currently does not explicitly require the result of arithmetic operations to be of the same type but I believe this is intended. You should ask https://github.com/JavaMoney/jsr354-api for clarification.

**Comment by keilw** [comment]
It is quite common to return a concrete type like `Money` in implementing classes and since `Money` implements `MonetaryAmount` using the API interface is always possible and the preferred way for interoperatbility.
