### ISSUE TITLE
missing method mentioned in javadoc

### ISSUE THREAD

**Issue by dominik42** [JavaMoney/jsr354-ri#192]
The javadoc for `org.javamoney.moneta.convert.ecb.ECBHistoricRateProvider.java` mentioned a method `javax.money.convert.ConversionQueryBuilder.setTimestamp` which doesn't exist. How should one load currency conversion rates for a specific date ? It is possible to load annual average conversion rates, or should we simply take the rate for e.g. 31.12.2017 as annual rate for 2017 for a given currency conversion ?

**Comment by wderose** [comment]
@dominik42 : I've been able to retrieve fx rates for a specific day by specifying the date in a `CurrencyConversionQuery`, like the example [here](https://github.com/MarSik/shelves-currency/blob/0b6e0a9fddeb2090c91569aed02958c07e8eeb96/src/main/java/org/marsik/elshelves/currency/services/OpenExchangeRatesClient.java#L27).

In my Scala code, I have:
```
val query = ConversionQueryBuilder.of
      .setRateTypes(RateType.DEFERRED)
      .setBaseCurrency(baseCurrency.toString)
      .setTermCurrency(termCurrency.toString)
      .set(dt)
      .build
val exchangeRate = MonetaryConversions.getExchangeRateProvider().getExchangeRate(query)
```

**Comment by dominik42** [comment]
cool, Thanks
