### ISSUE TITLE
OSGi manifest is missing imports and requires Java 9 runtime

### ISSUE THREAD

**Issue by rgchi** [JavaMoney/jsr354-ri#194]
Moneta-core (1.2.1) et al fails to load in an OSGi context with ClassNotFoundException / NoClassDefFoundError due to missing imports of packages `javax.annotation`, `org.osgi.framework` and `javax.money.*`.

Manifest also requires a newer java runtime than stated in docs (should target java 8) due to how bundle is generated:
```
Require-Capability = 
	osgi.ee;filter:=(&(osgi.ee=JavaSE)(version=9.0))
```

Suggested fixes will be submitted as a separate PR.

**Comment by keilw** [comment]
Thanks, please do. Although you may not be a JCP member, I would say a fix for the RI is highly welcome here and I see no reason not to accept/merge it.

**Comment by rgchi** [comment]
Thanks for quick response! Changes was submitted as PR #195 (already merged).
