### ISSUE TITLE
IMF rms_five.xls no longer parses because IMF changed case in money names

### ISSUE THREAD

**Issue by Oranor** [JavaMoney/jsr354-ri#197]
the rms_five.xls file that comes with moneta has the currecy names all starting with upper case like "Algerian Dinar". But since a few days IMF server uses "Algerian dinar", which fails to parse with moneta 1.2.1. Maybe the parser should convert currency names to lowercase first?

**Comment by keilw** [comment]
We could try to use `equalsIgnoreCase()` where relevant for 1.2.2 onward.

**Comment by heli80** [comment]
PR #200 should fix the issue.
