### ISSUE TITLE
IDENT exchange rate provider can be reduced

### ISSUE THREAD

**Issue by stokito** [JavaMoney/jsr354-ri#201]
> IDENT provides rates with a factor of 1.0, where base and target currency are the same.

First of all, we can add a case with zero amount: 0 is always 0 in any other currency.

But as for me this looks strange to have a rate provider for the case while this can be handled by rate provider caller because this is common logic for all rate providers.
Also from performance point of view the IDENT provider should be first in chain of providers but it is easy to forgot.
So can we get rid off the IDENT rate provider?
#

**Comment by stokito** [comment]
yes, I can make a PR latter but here I just wan't to know if this ok to do that or there is some use cases when it'\s better to have the IDENT provider.

**Comment by keilw** [comment]
Gotta ask @atsticks for the business case here.

**Comment by keilw** [comment]
@stokito You have not offered a PR for this, and looking at the module structure (e.g. isolating the IMF problems from the ECB problems I temporarily dismanteled the IMF module completely) `IdentityRateProvider` is declared in `moneta-convert-base` and works as the most minimalistic `ExchangeRateProvider` without any custom providers and modules enabled.
Could be a "Moneta Lite" in a future version if you want, so I think we should keep it for this sake.
