### ISSUE TITLE
Some format tests failing

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri#202]
While the overall build seems unaffected (ideally none should fail) there are failing tests seen in the latest build.

Failed tests: 
  MonetaryAmountFormatTest.testFormat:48 expected [12,50 CHF] but found [12,50 CHF]
  MonetaryAmountFormatTest.testFormatWithBuilder2:90 expected [12,50 756] but found [12,50 756]
  MonetaryAmountFormatTest.testParse:145 » MonetaryParse Unparseable number: "12...
  MonetaryAmountFormatTest.testPrint:111 expected [12,50 CHF] but found [12,50 CHF]
  MonetaryAmountFormatTest.testWithCustomPattern:172 expected [12.345,23 €] but found [12.345,23 €]

Some of them are extremely weird because the assertion does not make any sense.

**Comment by stokito** [comment]
duplicate of #208

**Comment by keilw** [comment]
That's why that one has been closed.

**Comment by stokito** [comment]
Let's close it as a duplicate of #193 because I fixed this issue with NBSP during a work on that issue

**Comment by stokito** [comment]
Fixed, please check and close the tocket
