### ISSUE TITLE
DefaultMonetaryAmountFormat fails when currency unit is not space-separated

### ISSUE THREAD

**Issue by git-developer** [JavaMoney/jsr354-ri#210]
The `DefaultMonetaryAmountFormat` throws an exception when parsing an amount from a format having no space character between amount and currency unit:

```java
import java.util.Locale;

import javax.money.Monetary;
import javax.money.MonetaryAmount;
import javax.money.MonetaryAmountFactory;
import javax.money.format.AmountFormatQueryBuilder;
import javax.money.format.MonetaryAmountFormat;
import javax.money.format.MonetaryFormats;

import org.testng.Assert;
import org.testng.annotations.Test;

@Test
public class Issue210 {

	private MonetaryAmountFormat createFormat(String pattern) {
		return MonetaryFormats.getAmountFormat(
				  AmountFormatQueryBuilder.of(Locale.GERMANY)
				                          .set(org.javamoney.moneta.format.CurrencyStyle.SYMBOL)
				                          .set("pattern", pattern)
				                          .build()
				);	}
	
	private MonetaryAmountFactory<?> createEURFactory() {
		return Monetary.getDefaultAmountFactory().setCurrency("EUR");
	}
	
	public void format() {
		double value = 1234.56d;
		MonetaryAmount amount = createEURFactory().setNumber(value).create();
		Assert.assertEquals(amount.getNumber().doubleValue(), value);

		MonetaryAmountFormat formatWithSpace = createFormat("#,##0.## ¤");
		String valueWithSpace = formatWithSpace.format(amount);
		Assert.assertEquals(valueWithSpace, "1.234,56 €");
		Assert.assertEquals(formatWithSpace.parse(valueWithSpace), amount); // works

		MonetaryAmountFormat formatWithoutSpace = createFormat("#,##0.##¤");
		String valueWithoutSpace = formatWithoutSpace.format(amount);
		Assert.assertEquals(valueWithoutSpace, "1.234,56€");
		Assert.assertEquals(formatWithoutSpace.parse(valueWithoutSpace), amount); // fails: javax.money.MonetaryException: Error parsing CurrencyUnit: no input.
	}
}
```

**Comment by stokito** [comment]
@odrotbohm that's not related to the problem with NBSP.
In fact the problem is that currently the logic of parser expect that the currency code from the input is always separated by a space no matter what the `pattern` is.
I'll try to fix that in scope of #193
Also I'll add your code as a test case.

**Comment by stokito** [comment]
This should be fixed in scope of #193 so please check and if it works please close the ticket

**Comment by odrotbohm** [comment]
Lovely, Sergey! Thanks for that. Is there a place I can find out about how to use preview versions of Moneta (snapshot builds etc.)?

**Comment by keilw** [comment]
YES, you may use those repositories in a POM like https://github.com/JavaMoney/javamoney-examples/blob/master/pom.xml shows.

**Comment by stokito** [comment]
@keilw  maybe we should mention those repositories in README or somewhere else.
For now you can check the unit test `MonetaryAmountFormatTest.testWithCustomPattern`.

**Comment by keilw** [comment]
@stokito Not sure, if everyone can republish the site, but please feel free to raise PRs for https://javamoney.github.io/api.html or https://javamoney.github.io/ri.html to mention Snapshot repositories, too.

**Comment by odrotbohm** [comment]
I can see the sort of related #208 fixed with the current 1.4 snapshots.

**Comment by stokito** [comment]
@odrotbohm it's not clear for me: is it fixed or not? 
BTW the SalesPoint framework looks similar to what I developing on the current job. Is it used somewhere in prod? Will investigate it and maybe I can contribute a little bit

**Comment by odrotbohm** [comment]
It is. I am preparing the upgrade to JDK 11 in [this commit](https://github.com/st-tu-dresden/salespoint/commit/27ce6bb05691c864946050a4c40ea7ffe07ddba5), the test cases previously failed but are back to green on 1.4 snapshots.

I don't think Salespoint is in production anywhere. It's sole purpose is to support students in writing POS web applications on top of it during the software engineering lab. That means, in quite a few parts of the library we made decisions based on an enhanced need for simplicity that might be suboptimal ones if you really wanted to take it into production.

**Comment by git-developer** [comment]
When I run the test above on JDK8 using `moneta:1.4-SNAPSHOT` from the [SNAPSHOT repository](http://oss.jfrog.org/artifactory/oss-snapshot-local), the following exception occurs on the first call of `createFormat(String)`:
```
javax.money.MonetaryException: No MonetaryAmountFormat for AmountFormatQuery AmountFormatQuery (
{pattern=#,##0.## ¤, Query.formatName=default, org.javamoney.moneta.format.CurrencyStyle=SYMBOL, java.util.Locale=de_DE})
```
Am I missing something?

**Comment by git-developer** [comment]
`org.javamoney.moneta.internal.format.DefaultAmountFormatProviderSpi.getAmountFormats(AmountFormatQuery)` returns an empty set because the query does not contain any provider names. Is this the expected behavior?

**Comment by git-developer** [comment]
Works now, thanks!

**Comment by odrotbohm** [comment]
Any plans to package this fix in a release. The snapshots fix the issue but until a release is available Moneta cannot be used in a project on a Java version better than 8. 😕

**Comment by keilw** [comment]
We plan the MR1 as soon as all showstoppers are fixed in the RI and RI-BP. Think we should be pretty close, with only one or the other issue left.

**Comment by odrotbohm** [comment]
Thanks, Werner, appreciated! 🙏

**Comment by keilw** [comment]
You're welcome. Anybody who has an opinion from a practical point of view, please check https://github.com/JavaMoney/jsr354-ri/issues/275 (the only bug with a higher priority) if you feel it should go into MR1 or could wait till a new JSR?
