### ISSUE TITLE
MonetaryAmountFormat.format with negative value adds an extra "-" after the currency symbol.

### ISSUE THREAD

**Issue by martinstraus** [JavaMoney/jsr354-ri#211]
This:

```@Test
    public void formatNegativeValueFor_es_AR() {
        MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(
            AmountFormatQueryBuilder.of(new Locale("es", "AR")).set(CurrencyStyle.SYMBOL).build()
        );
        assertThat(
            "negative value",
            format.format(Money.of(-1, Monetary.getCurrency("ARS"))),
            is("$-1,00")
        );
    }
```

Fails with this error:

```java.lang.AssertionError: negative value
Expected: is "$-1,00"
     but: was "$--1,00"
```
There's an extra "-" between "$" and "1". Am I doing something wrong instantiating the format?

I'm using version 1.1

**Comment by martinstraus** [comment]
I've tracked this to ```org.javamoney.moneta.internal.format.DefaultMonetaryAmountFormat.setAmountFormatContext(AmountFormatContext)```, line 242:

```
 initPattern(plusMinusPatterns[1], this.negativeTokens, amountFormatContext);
```
Here, negativeTokens is initialized with the negative pattern, say ```-#,##```. Inside ```AmountNumberToken```, this pattern is applied to ```formatFormat```, like this:

```
 formatFormat.applyPattern(this.partialNumberPattern);
```

But [```BigDecimal```'s JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html) says

> The negative subpattern is optional; if absent, then the positive subpattern prefixed with the localized minus sign ('-' in most locales) is used as the negative subpattern. That is, "0.00" alone is equivalent to "0.00;-0.00"

Thus, ```-#,##``` is the positive pattern, which is equivalent to ```-#,##;--#,##```; hence, the minus sign is duplicated in the inferred negative pattern.

**Comment by keilw** [comment]
Thanks @martinstraus can you test it with master and close this if the problem was resolved?
