### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by guofengzh** [JavaMoney/jsr354-ri#234]
The following is how the providers are initialized:
`public static final ExchangeRateProvider rateProvider = MonetaryConversions.getExchangeRateProvider("ECB", "IMF");`
Then in a constructor:
`conversion = rateProvider.getCurrencyConversion(termCurrencyUnit);`
When I convert moneys, it worked very well before. But recently I find the conversions are always failed. 

I check that the data files downloaded from ECB are HTML files with tile "301 Moved Permanently". 

the related files are attached.

[301-error.zip](https://github.com/JavaMoney/jsr354-ri/files/2431588/301-error.zip)

**Comment by guofengzh** [comment]
Forget the version information:
    Java Money 1.3, Java 10, 

There are 3 application using Java Money on the same machine on AWS in Korea (.resourceCache allocated to different directory by -Dtemp.dir). The one of them always works well, and the other two always failed as reported.

Now I changed the way like javamoney-console-simple：
          conversion = MonetaryConversions.getConversion(termCurrency, PROVIDER_IMF);
It works well now on AWS .

I just run ConversionExample in my home computer, it works well (also on Java 10.0.2):

**Comment by keilw** [comment]
Sounds more like some routing or firewall problem, especially if all 3 of the mentioned apps run the same combination of JavaMoney and JDK. Please confirm, they all do, then I assume we should collect that kind of issue and remedy under "Known Issues" in a new JavaMoney guide book or GitBook.

**Comment by guofengzh** [comment]
Yes. the same Oracle JDK 10.0.2, and Java monery 1.0.3 (sharing the same parent pom, but packaged to separate jar)

**Comment by guofengzh** [comment]
Yes. the same Oracle JDK 10.0.2, and Java monery 1.3 (sharing the same parent pom, but packaged to separate jar)

**Comment by keilw** [comment]
Thanks, then I'd say this is nothing related to JavaMoney/Moneta as such. If the workaround helps those apps in question, let's keep it in mind for either howtos or future documentation, but I'm afraid there is no immediate action here on the JavaMoney side.
