### ISSUE TITLE
Inconsistent formatting white space

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-ri#261]
The project uses a mix of spaces and tabs, for example see
https://github.com/JavaMoney/jsr354-ri/blob/master/moneta-core/src/test/java/org/javamoney/moneta/format/MonetaryFormatsTest.java
it would be could if the project could settle on one style and apply it consistently.

**Comment by stokito** [comment]
I think we should setup some checkstyle plugin to avoid such problems in the feature. Code style should be similar to OpenJDK i.e. spaces.

**Comment by keilw** [comment]
Is this about https://github.com/JavaMoney/jsr354-ri/issues/193 or just code format? Again, these are nice to have, but we can leave this for later, the important thing is the functional outcome of Monetary parsing.

**Comment by marschall** [comment]
@keilw this is not related to #193 but about the code style of the source files.
