### ISSUE TITLE
Inconsistent formatting overridden method

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-ri#262]
The project uses an inconsistent style for overridden methods

Some methods are just
```java
    @Override
```

while others are
```java
    /*
         * (non-Javadoc)
         * @see
         * javax.money.spi.MonetaryAmountFormatProviderSpi#getFormat(javax.money.format.AmountFormatContext)
         */
    @Override
```

For an example see
https://github.com/JavaMoney/jsr354-ri/blob/master/moneta-core/src/main/java/org/javamoney/moneta/internal/format/DefaultAmountFormatProviderSpi.java

**Comment by keilw** [comment]
This is also cosmetic. Different users may have done with different editors or IDEs. Please let's focus on functional defects for the MR and leave other items for upcoming new JSRs.

**Comment by marschall** [comment]
Absolutely, it's cosmetic and low priority. I was not suggesting a priority, or release date.

**Comment by keilw** [comment]
I did add priorities (similar to many Jakarta EE projects, any suggestion to tweak them for our needs is welcome) to most issues. With the functional formatting and parsing discrepancies as highest for now.

**Comment by keilw** [comment]
We'll probably forget about the non-JavaDoc in the future, but there is no point removing the existing ones, closing this.
