### ISSUE TITLE
CurrencyToken ignores AmountFormatContext provider name

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-ri#276]
I stumbled upon this and I am not sure whether this is a bug or not.

`org.javamoney.moneta.internal.format.CurrencyToken.parse(ParseContext)` uses `javax.money.Monetary.getCurrency(String, String...)` but does not pass the provider name from `javax.money.AbstractContext.getProviderName()`. Instead it passes no provider name at all so all possible providers are considered.

**Comment by stokito** [comment]
Yes, this is a bug and should be fixed

**Comment by keilw** [comment]
Seems like a bug, but IMO not as severe as some of the others that affect how values are parsed or formatted.

**Comment by atsticks** [comment]
Attention: the provider name of the formatting context defines references the formatting provider.
Instead we talk here about a currency porovider, which as of now cannot be set.
So I will add support for a property "currencyProviderName' and honor this one.

**Comment by atsticks** [comment]
Fixed.
