### ISSUE TITLE
Money formatting: Literals in pattern may not work

### ISSUE THREAD

**Issue by stokito** [JavaMoney/jsr354-ri#281]
Please take a look on the `AmountNumberTokenTest#testParse_with_literals_in_patern` test:
```java
    @Test
    public void testParse_with_literals_in_patern() {
        testParse(US, "#,##0.00 ", null, "-123.45", 7, "without literal", -123.45, "-123.45");
        testParse(US, "BEFORE #,##0.00 ", null, "BEFORE 123.45", 13, "Literal on start", 123.45, "BEFORE 123.45");
//FIXME        testParse(US, "ONE TWO #,##0.00 ", "ONE TWO -123.45", 7, "Two literals on start", -123.45);
    }
```

The last assert doesn't work because it parsed incorrectly to LiteralToken.

**Comment by atsticks** [comment]
The same is with pre and postfix literals. The problems are identified as follows:
1. The prefix `LiteralToken `is created.
2. The `AmountToken `is created, but its `DecimalFormat `also contains the literal parts (pre and suffix).
3. There is no corresponding suffix `LiteralToken`, if one should be present.

See debugger for `"LITERAL ¤ #,##0.## LITERAL"` pattern:

![image](https://user-images.githubusercontent.com/3042419/71782347-475e6a00-2fd9-11ea-9532-1c76154f8a11.png)

Fix:

1. Add a post LiteralToken if a postliteral is present.
2. Cut off the "literal parts" from the amount pattern used by `AmountToken`.

Then things should work as designed.

**Comment by atsticks** [comment]
Works now.
