### ISSUE TITLE
Too many userguide.adoc files

### ISSUE THREAD

**Issue by stokito** [JavaMoney/jsr354-ri#293]
I'm confused because it's at least 5 files `userguide.adoc` with exactly the same content. Do we need them all? 
And BTW can we convert it from AsciiDoc to Markdown? Because it's much more devs who knows MD, in the same time ADoc doesn't give us too much. Almost everything can be easily rewritten to MD

**Comment by stokito** [comment]
In scope of  #306 I migrated the userguide to MD format.
My next proposition is to remove all others usrguide.adoc files and maybe even move the file to  github's wiki for the moneta repo. Thus it will be easier to contribute and to split the big document so separate pages.

**Comment by keilw** [comment]
Please don't convert anything to MD. We may have accidentally duplicated some ADOC files when we split up into modules, but the idea is to have a modular documentation along the lines of https://redhat-documentation.github.io/modular-docs/ and with Asciidoc this is more likely to work. Whether or not the User Guide should be here or in a separate repository, that is another question, feel free to create a question ticket.

**Comment by keilw** [comment]
Actually this makes sense, it is for each module. We could think of a better naming or mention the module in the filename, but for now let's leave it until the next version.
