### ISSUE TITLE
Lenient Formatter: Parse a string with a number but without a currency code

### ISSUE THREAD

**Issue by stokito** [JavaMoney/jsr354-ri#294]
There is a question of [StackOverw](lohttps://stackoverflow.com/questions/36874805/customizing-a-monetaryamountformat-using-the-moneta-javamoney-jsr354-implemena/36948559) about how to parse number without currency code/symbol.

If you are using a custom format pattern then you can parse strings which contains only a number without currency but you should specify the expected currency yourself.
Here is an example:
```java
    @Test
    public void testParse_pattern_without_currency_sign_but_with_currency_in_context() {
        CurrencyUnit usd = Monetary.getCurrency("USD");
        AmountFormatContextBuilder builder = AmountFormatContextBuilder.of(US);
        builder.set(AmountFormatParams.PATTERN, "0.00"); // the pattern doesn't contains a currency sign ¤
        builder.set(CurrencyUnit.class, usd); // set expected currency
        AmountFormatContext context = builder.build();
        DefaultMonetaryAmountFormat format = new DefaultMonetaryAmountFormat(context);
        MonetaryAmount parsedAmount = format.parse("0.01 USD");
        assertSame(parsedAmount.getCurrency(), usd);
        assertEquals(parsedAmount.getNumber().doubleValueExact(), 0.01D);
        assertEquals(parsedAmount.toString(), "USD 0.01");
    }
```

Note that you need to create a context with `set(CurrencyUnit.class, usd)`.

But if you try to set a pattern with with the currency sign e.g. `0.00 ¤` then you'll receive an error: 
```
javax.money.format.MonetaryParseException: Error parsing CurrencyUnit: no input.
	at org.javamoney.moneta.internal.format.CurrencyToken.parse(CurrencyToken.java:184)
	at org.javamoney.moneta.internal.format.DefaultMonetaryAmountFormat.parse(DefaultMonetaryAmountFormat.java:156)
```

In the `CurrencyToken.java:184` there is a check for this:
```java
        if (token == null) {
            throw new MonetaryParseException("Error parsing CurrencyUnit: no input.", "", -1);
        }
```

So in fact the `CurrencyToken` decides to throw the exception while actually this should be decided on higher level i.e. inside of `org.javamoney.moneta.internal.format.DefaultMonetaryAmountFormat#parse`.

Thus you can't parse an amount without currency code/symbol with locale's default pattern instead of a custom pattern:
```java
    @Test
    public void testParse_amount_without_currency_code_but_with_currency_in_context() {
        CurrencyUnit usd = Monetary.getCurrency("USD");
        final MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(
            AmountFormatQueryBuilder.of(US)
                .set(CurrencyUnit.class, usd)
                .build()
        );
        MonetaryAmount parsedAmount = format.parse("0.01 USD");
        assertSame(parsedAmount.getCurrency(), usd);
        assertEquals(parsedAmount.getNumber().doubleValueExact(), 0.01D);
        assertEquals(parsedAmount.toString(), "USD 0.01");
    }
```
This fails with:
```
javax.money.format.MonetaryParseException: Could not parse CurrencyUnit. Unknown currency code: 
	at org.javamoney.moneta.internal.format.CurrencyToken.parse(CurrencyToken.java:232)
	at org.javamoney.moneta.internal.format.DefaultMonetaryAmountFormat.parse(DefaultMonetaryAmountFormat.java:156)
```

So if our users are forced to always specify the patterns themselves. Which means that we have half broken functionality.

In the same time the usual `java.text.DecimalFormat` also can't parse amount if it doesn't contains a currency code:
```java
    @Test
    public void testParseAmountWithoutCurrency() throws ParseException {
        DecimalFormat format = (DecimalFormat) DecimalFormat.getCurrencyInstance(Locale.US);
        format.setCurrency(Currency.getInstance("USD"));
        Number parsed = format.parse("42.25");
        Assert.assertEquals(parsed, 42.25D);
    }
```
This fails with `java.text.ParseException: Unparseable number: "42.25"`.
But if you change the `(DecimalFormat) DecimalFormat.getCurrencyInstance(Locale.US)` to `(DecimalFormat) DecimalFormat.getNumberInstance(Locale.US)` it will parse.

So the users of `DecimalFormat` have [exactly the same problem](https://stackoverflow.com/questions/15586099/numberformat-parse-fails-for-some-currency-strings)

So my considerations are:
1. Since we already have some logic that allows to parse amounts without currency code/symbol then we should extend it to not fail if the pattern anyway contains the currency sign ¤ and the expected currency was set via `set(CurrencyUnit.class, usd)`. We can treat this like a bug.
2. We can change the logic of formatters to make them lenient (or introduce a lenient mode) and do not throw parse exceptions and parse what we can: if we were able to parse amount then store it to a `number` field, if we were able to parse a currency then store it to `currency` field and if they both was parsed then we can store result in `money` field or store a `null` there otherwise.
Thus users can check themselves if the parsing was full or partial.

**Comment by atsticks** [comment]
Fixed.
