### ISSUE TITLE
ConfigurableCurrencyUnitProvider does not support searching by numeric code

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-ri#308]
ConfigurableCurrencyUnitProvider only supports searching by currency code or by locale. A search by numeric code returns all currencies.

The issue seems to be that `org.javamoney.moneta.internal.ConfigurableCurrencyUnitProvider#registerCurrencyUnit(CurrencyUnit)` only registers the currency code and not the numeric code

https://github.com/JavaMoney/jsr354-ri/blob/cf8ff2bbaf9b115acc05eb9b0c76c8397c308284/moneta-core/src/main/java/org/javamoney/moneta/internal/ConfigurableCurrencyUnitProvider.java#L82

**Comment by keilw** [comment]
@marschall Thanks for the PR, do you think it can be offered to the BP as well, or do you think it's acceptable to only do it in Moneta? I am a bit undecided on that one, while core parsing must work in both.

**Comment by marschall** [comment]
I don't see a reason why it couldn't be offered in the backport, the classes look similar enough. Obviously currency code queries will behave differently.
OTOH if nobody reported it sofar then it is probably less important.
Unfortunately I likely won't have time to backport #310 but if somebody else wants to pick it up I'd be happy to do a review.

**Comment by acelopezco** [comment]
Hi @marschall thanks for your contributions. I can do the backport. However, I'd like to discuss a little further your last [PR#310 comment](https://github.com/JavaMoney/jsr354-ri/pull/310#issuecomment-513541572).  I'm not sure which Interface change you are talking about. Also, I think the toString() method needs to be changed as well.

I like the idea of having just one register* remove* method for both currencyCodes and numericCodes so they are synced.

**Comment by marschall** [comment]
> Also, I think the toString() method needs to be changed as well.

Done.

> I'm not sure which Interface change you are talking about. 
>
> I like the idea of having just one register* remove* method for both currencyCodes and numericCodes so they are synced.

We currently have:
* `ConfigurableCurrencyUnitProvider#registerCurrencyUnit(CurrencyUnit)` which registers only by currency code
* `ConfigurableCurrencyUnitProvider#registerCurrencyUnit(CurrencyUnit, Locale)` which registers only by locale
* `ConfigurableCurrencyUnitProvider#removeCurrencyUnit(String)` which unregisters only by currency code
* `ConfigurableCurrencyUnitProvider#removeCurrencyUnit(Locale)` which unregisters only by locale

Rather than add an additional `#register*` and `#remove*` method only for numeric code I extended the existing ones for the currency code.

A third option would be to have only two methods
*  `ConfigurableCurrencyUnitProvider#registerCurrencyUnit(CurrencyUnit, Locale)` which registers by currency code, optionally by numeric code, optionally by Locale
* `ConfigurableCurrencyUnitProvider#removeCurrencyUnit(String)` which unregisters by currency code, optionally by numeric code, optionally by Locale

However that would break the public interface of `ConfigurableCurrencyUnitProvider`. We could argue that `ConfigurableCurrencyUnitProvider` is in the `org.javamoney.moneta.internal` which registers only by currency codepackage in therefore not API

**Comment by acelopezco** [comment]
This is the backport PR: https://github.com/JavaMoney/jsr354-ri-bp/pull/56
