### ISSUE TITLE
JDKCurrencyProvider and ConfigurableCurrencyUnitProvider do not implement regex currency code searching

### ISSUE THREAD

**Issue by marschall** [JavaMoney/jsr354-ri#309]
`javax.money.CurrencyQueryBuilder#setCurrencyCodes(String...)` specifies that a regex can be for searching by currency code

https://github.com/JavaMoney/jsr354-api/blob/49a7ae436eaf45cac1040879185531ef22de5525/src/main/java/javax/money/CurrencyQueryBuilder.java#L63

However JDKCurrencyProvider and ConfigurableCurrencyUnitProvider only implement exact matches. I believe I would come up with a test case.

**Comment by atsticks** [comment]
Fixed, test activated (and fixed ;-) ).
