### ISSUE TITLE
new Release with full jpms support

### ISSUE THREAD

**Issue by chrismaster** [JavaMoney/jsr354-ri#317]
Are there any plans to make a release and upload it to some public maven repository?
Cant use 1.3 any more, cause of some jpms problems fixed in the snapshots.
Thx

**Comment by keilw** [comment]
I meet with @atsticks next week when we present the JSR at JCON. We plan to file the MR (1.4 of the RI) shortly after that, when the CP is also back from Oracle Code1.

**Comment by ptahchiev** [comment]
Yep, I'm also waiting on a release to finally have this fixed null-pointer exception
https://github.com/JavaMoney/jsr354-ri/pull/214

**Comment by keilw** [comment]
We aim for a MR1 after the end of the year, so the new and many of them first time JCP EC Members can get accustomed to their duties and some key contributors including @atsticks or myself had a few days to help with open issues.

**Comment by keilw** [comment]
#214 is closed, so can this be closed, too?

**Comment by chrismaster** [comment]
With 1.4 snapshots jpms works. Is there a release plan for 1.4 or maven link for 1.4-snapshot?

**Comment by keilw** [comment]
This will be part of the MR1 of [JSR 354](https://jcp.org/en/jsr/detail?id=354) We hope to file it soon (it's not like the JCP EC has too much to do now ;-)
