### ISSUE TITLE
getCurrencies has a bug initializing in concurrency， No currency unit found

### ISSUE THREAD

**Issue by Yaccc** [JavaMoney/jsr354-ri#318]
when I use ```Monetary.getCurrency(Locale.CHINA)``` The following exception will be generated
```java
Caused by: javax.money.MonetaryException: No currency unit found for locale: zh_CN
at javax.money.spi.MonetaryCurrenciesSingletonSpi.getCurrency(MonetaryCurrenciesSingletonSpi.java:97)
at javax.money.Monetary.getCurrency(Monetary.java:439)
```
And the program doesn't automatically restore
When I restarted the process, the program returned to normal and never appeared again~~
my moneta verison is ```<version>1.1</version>```

then,I find the issues #158  very similar to mine. Is that a problem? thx very much

**Comment by keilw** [comment]
Please try with Moneta at least version 1.3. Can you still reproduce the problem there?

**Comment by Yaccc** [comment]
> Please try with Moneta at least version 1.3. Can you still reproduce the problem there?

1.3 there is no such problem

**Comment by Yaccc** [comment]
so，I think this case is similar to #158，right？

**Comment by keilw** [comment]
Thanks for confirming that, guess it can be closed then? Yes, they sound related.

**Comment by Yaccc** [comment]
> Thanks for confirming that, guess it can be closed then? Yes, they sound related.

👌
