### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nemphys** [JavaMoney/jsr354-ri#325]
I think it should be time to make a new release, it's been 1.5 years since the last one :-)
I am especially interested in the Java9+ compatibility issue that has been fixed with #302 since last April.
It is a shame having to locally build the whole library for just a small change instead of getting it automatically with maven/gradle.

**Comment by keilw** [comment]
We're working on the MR1, and this RI looks relatively good, but unless the JCP PMO/EC allowed us to simply abandon the BP in a Maintenance Release you're more than welcome to help with the showstopper bugs in the RI-BP: https://github.com/JavaMoney/jsr354-ri-bp/issues?q=is%3Aissue+is%3Aopen+label%3Ashowstopper
