### ISSUE TITLE
Release 1.4.1 is not available in central

### ISSUE THREAD

**Issue by fatroom** [JavaMoney/jsr354-ri#337]
Hi @keilw 
congrats on the new release. I'm using dependabot for one of my private projects, and it's detected the release 1.4.1 of this library. But CI build is failed due to missing dependency. Would you mind to upload the released version to central please?

https://search.maven.org/artifact/org.javamoney/moneta shows only 1.4 as last released version.

**Comment by keilw** [comment]
Please wait till the end of the day, syncing to MavenCentral always takes a few hours, but if you are very eager, Bintray JCenter already has every dependency.

**Comment by keilw** [comment]
In a few hours please check manually, if all artifacts except moneta-bp (we don't plan to support it much unless there is a major bug and especially Jigsaw improvements don't matter to Java 7) in this list https://search.maven.org/search?q=moneta show 1.4.1. If you are missing one, please comment here.

**Comment by fatroom** [comment]
Everything is available on central right now. Thank you!
