### ISSUE TITLE
Missing JARs for 1.4.x in official Maven Repos

### ISSUE THREAD

**Issue by markieww** [JavaMoney/jsr354-ri#339]
No JAR files of the releases 1.4.* are available anymore. Only *.pom files.

Please check.
https://repo1.maven.org/maven2/org/javamoney/moneta/1.4.2/
https://repo1.maven.org/maven2/org/javamoney/moneta/1.4.1/
https://repo1.maven.org/maven2/org/javamoney/moneta/1.4/

https://oss.jfrog.org/artifactory/oss-release-local/org/javamoney/moneta/1.4.2/
https://oss.jfrog.org/artifactory/oss-release-local/org/javamoney/moneta/1.4.1/
https://oss.jfrog.org/artifactory/oss-release-local/org/javamoney/moneta/1.4/

**Comment by keilw** [comment]
Yes that's exactly how it's supposed to be. Every version since 1.3 Moneta has been modular and you need to use it as a "BOM", see https://github.com/JavaMoney/javamoney-examples/blob/master/console/javamoney-console-simple/pom.xml

**Comment by ToppScorer** [comment]
Sorry, but this can not be used, how a BOM is supposed to be used. When importing the BOM

``` 
<dependency>
  <groupId>org.javamoney</groupId>
  <artifactId>moneta</artifactId>
  <version>1.4.2</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```

you should be able to import the artifacts without using the version number:

```
<dependency>
  <groupId>org.javamoney</groupId>
  <artifactId>moneta-core</artifactId>
</dependency>
```

but this is not possible, as the `groupId` is not the same. 

If you try to use:

```
<dependency>
  <groupId>org.javamoney.moneta</groupId>
  <artifactId>moneta-core</artifactId>
</dependency>
```

the `version` is missing from the dependency.

**Comment by keilw** [comment]
As this is the Moneta Parent POM the version number in dependency management is totally fine.

**Comment by ToppScorer** [comment]
Not sure what you mean by this. How is you "BOM" supposed to be used? Can you give an example where only the `moneta-core` module would be included in a project?

**Comment by keilw** [comment]
Check out https://github.com/JavaMoney/javamoney-examples

**Comment by ToppScorer** [comment]
I think the problem is, that your "BOM" already defines dependencies and not only versions, what BOMs should only do.

**Comment by keilw** [comment]
Well somewhere you must define them, otherwise you won't find any, but defining a "BOM" is up to you, the examples work the way they are.
