### ISSUE TITLE
Not possible to get currency symbol out of CurrencyUnit?

### ISSUE THREAD

**Issue by lehphyro** [JavaMoney/jsr354-ri#344]
Hi, given a `CurrencyUnit` instance, is it really not possible to get a symbol out of it? Not even through some formatter?

**Comment by keilw** [comment]
Of course it's possible, but not every `CurrencyUnit `(or the code behind it) may have a `java.util.Currency` symbol available.
Use something like
```
var amt = Money.of(5, "USD");        System.out.println(MonetaryFormats.getAmountFormat(AmountFormatQueryBuilder.of(Locale.US).set(CurrencyStyle.SYMBOL).set(AmountFormatParams.PATTERN, "¤##.##").build()).format(amt));
```
as in [FormattingAmounts (Java10)](https://github.com/JavaMoney/javamoney-examples/blob/master/console/javamoney-console-java10/src/main/java/org/javamoney/examples/console/java10/format/FormattingAmounts.java).
