### ISSUE TITLE
Can't load ExchangeRateProviders properly / Moneta 1.4.1

### ISSUE THREAD

**Issue by 0x00b7** [JavaMoney/jsr354-ri#350]
I wanted to write a simple service using the RI of JSR354, but when I try to load the ExchangeRateProvider I encounter a lot of java.net.SocketTimeoutException: connect timed out.

Basically, if I start the service this exceptions are thrown multiple times. Moneta starts to load the sources remotely and after about a minute the service runs and according to the log the Date for the Providers are loaded successfully. But when I try to convert, I will always get results for historic exchange rates, which seem to be loaded from the default values for each provider.
If I want to use the ECB as a provider
`rateProvider = MonetaryConversions.getExchangeRateProvider("ECB");`
I will get the exchange rates from the ECB default .xml which is for 2016-01-08

I am working from home from my companys laptop which uses a VPN to connect to the companys network and the connection also goes through a proxy. At first I thought that this might be a problem but when I tried to run my code from my private laptop I have the same issue.

If i try to use the exchange rate of any other day by writing a conversion query, I will get the following exception:
`Request processing failed; 
nested exception is CurrencyConversionException [base=EUR, term=USD, conversionContext=null]: 
Cannot convert EUR into USD: 
Rate Provider did not return data though at check before data was flagged as available, provider=IMF, 
query=ConversionQuery ( {Query.termCurrency=USD, Query.baseCurrency=EUR, java.time.LocalDate=2021-01-01})`

The complete code for the service is:
`public class CurrencyActions {
    ExchangeRateProvider rateProvider;

    public CurrencyActions() {
        rateProvider = MonetaryConversions.getExchangeRateProvider();
    }

    public String conversionProcess(double fromAmount, String fromCurrency, String toCurrency) {
        return returnFormattedResult(convertCurrency(fromAmount, fromCurrency, toCurrency));
    }

    public Money convertCurrency(double fromAmount, String fromCurrency, String toCurrency) {
        Money fromMonetaryAmount = Money.of(fromAmount, fromCurrency);
        CurrencyConversion conversion = rateProvider.getCurrencyConversion(toCurrency);
        return fromMonetaryAmount.with(conversion);
    }

    public String returnFormattedResult(MonetaryAmount resultMonAmount) {
        MonetaryAmountFormat formatCountry = MonetaryFormats.getAmountFormat(GERMAN);
        return formatCountry.format(resultMonAmount);
    }`

EDIT: I am sorry this is my first post on GitHub and I dont't know why the first part of the code isn't properly formatted as code

**Comment by keilw** [comment]
This sounds like a network problem. If you are in home-office the connection might have issues regardless of proxy or VPN, there is not much to help with that I'm afraid. Note, you should try using the latest 1.4.2 version of Moneta, although I doubt it may help you with the network issue, but some smaller problems in other areas were fixed between 1.4.1 and 1.4.2.
Network connectivity or even blockage of access to certain countries and services whether it's ECB or IMF does happen, even in countries that do not restrict or censor the internet of their citizens on a regular basis.
There are so many use cases in production as we speak with big vendors like Zalando, but some of them have their own exchange rate providers in-house and may not always use the default free ones. 

Please use the latest version of Moneta and ask the support team of either your company or internet provider if you face network latency problems.
