### ISSUE TITLE
Money.toString() logs usage of default formatter to INFO level

### ISSUE THREAD

**Issue by odrotbohm** [JavaMoney/jsr354-ri#351]
This is creating a lot of iiritating noise in the logs, especially as the method causing it (`defaultFormatter()`) is not only called from `toString()` but e.g. also from `….parse(CharSequence)`.

What's the purpose of that output. Is it, to signal that one should rather use a dedicated format instead? If it's really just general information, does it make sense to rather move this to the `DEBUG` level?

**Comment by keilw** [comment]
Isn't this what https://github.com/JavaMoney/jsr354-ri/pull/349 was created for?
There is no `DEBUG` level in the JDK logging, only FINE (unless they started calling it differently again in the new Java 9 loggers?)

**Comment by odrotbohm** [comment]
You're right. I only looked in the issues for "log" but didn't do so for pull requests.
