### ISSUE TITLE
Incorrect subunit calculation for CZK

### ISSUE THREAD

**Issue by sambaranhazra** [JavaMoney/jsr354-ri#360]
Czech Koruna has defunct currency subunit since [2008](https://en.wikipedia.org/wiki/Czech_koruna), though moneta calculation allows without rounding up to next integral.

```java
public void testCurrencyCZK() {
        MonetaryAmount amount = Monetary.getDefaultAmountFactory()
            .setCurrency(Monetary.getCurrency("CZK"))
            .setNumber(207)
            .create();
        System.out.println(amount.multiply(0.34));
    }
```
results into 
```CZK 70.38``` which is incorrect

**Comment by keilw** [comment]
Thanks for pointing that out. What would be correct to drop the 38 and how does rounding happen in CZ now, could you point us to a source like the national bank etc.?

**Comment by keilw** [comment]
In fact based on the Wikipedia quote 
> 2008 due to their diminishing purchasing power and circulation.[9] However, financial amounts are still written with the accuracy of 1-haléř (CZK 0.01); prices in retail shops are usually multiples of CZK 0.10. When transactions are made, the amount is rounded to the nearest integer.

**Comment by sambaranhazra** [comment]
Thanks for having a look into this, so does it mean it depends on the cash/electronic payment method and needs to be handled specific to the payment method where it's being applied on?

**Comment by keilw** [comment]
Yes but that's not something Moneta would do for you, if you have an application you may have a payment method like "Cash", "Card", "Paypal", "Apple Watch" or who knows what else exists nowadays that different vendors and applications offer, that is domain-specific and could not be covered by JSR 354 or the JDK. So I'd say this is out of scope here and given the complexity and variety of payment options it may never be subject to this or other JSR implementations.
