### ISSUE TITLE
Formatting for BRL causes exception

### ISSUE THREAD

**Issue by Robson96** [JavaMoney/jsr354-ri#363]
**pom.xml**
```
<dependency>
      <groupId>javax.money</groupId>
      <artifactId>money-api</artifactId>
      <version>1.1</version>
 </dependency>
 <dependency>
      <groupId>org.javamoney</groupId>
      <artifactId>moneta</artifactId>
      <version>1.4.1</version>
      <type>pom</type>
  </dependency>
```

**Error**
![money](https://user-images.githubusercontent.com/53229150/125111603-7c5ee780-e0bc-11eb-813b-67ecf4929956.png)

**Comment by keilw** [comment]
Have you tried this with a later version, at least 1.4.2 is already out?

@otaviojava any thoughts from a Brazilian on that?

**Comment by Robson96** [comment]
![money2](https://user-images.githubusercontent.com/53229150/125112353-70275a00-e0bd-11eb-9563-24df67ad5197.png)
the bug still persists

**Comment by Daniel-Dos** [comment]
Hello, 

work like this: 

`final MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(new Locale ("pt", "BR"));`

if you want to change the format you can use:

```
final MonetaryAmountFormat format = MonetaryFormats.getAmountFormat(
			      AmountFormatQueryBuilder.of(new Locale ("pt", "BR"))
			        .set(CurrencyStyle.NAME)
			        .build()
			    );
```

**Comment by keilw** [comment]
@Daniel-Dos Great thanks, so no codechange in the JSR or RI required it seems?
If you want and can you could provice an example under https://github.com/JavaMoney/javamoney-examples and close this ticket if it works that way.

**Comment by Daniel-Dos** [comment]
you don't need to change anything in the RI and not in the API.

It works perfectly :)

follow the example

https://github.com/JavaMoney/javamoney-examples/pull/47

**Comment by keilw** [comment]
Then with the example from JavaMoney/javamoney-examples#47 this can be closed.
