### ISSUE TITLE
DuplicateRelativeFileException when importing library in Android Studio

### ISSUE THREAD

**Issue by slaviboy** [JavaMoney/jsr354-ri#394]
When I try to import this Java library in Android Studio

```
implementation("org.javamoney:moneta:1.4.2")
```
----

 I get the following error:
```
com.android.builder.merge.DuplicateRelativeFileException: 3 files found with path 'javamoney.properties' from inputs:

 - C:\Users\Slaviboy\.gradle\caches\modules-2\files-2.1\com.github.JavaMoney.jsr354-ri\moneta-convert-ecb\1.4.2\cd734dec35de5693e50836af4787c5a876bec42c\moneta-convert-ecb-1.4.2.jar
 - C:\Users\Slaviboy\.gradle\caches\modules-2\files-2.1\com.github.JavaMoney.jsr354-ri\moneta-convert-imf\1.4.2\8e4775e5bd2328a0accef2c8fd5ff469b457e1be\moneta-convert-imf-1.4.2.jar
 - C:\Users\Slaviboy\.gradle\caches\modules-2\files-2.1\com.github.JavaMoney.jsr354-ri\moneta-core\1.4.2\7ec7364585dc47278dea9f5787390dec0a456f\moneta-core-1.4.2.jar
```

Is it possible to include and use this library with Android Studio?

**Comment by slaviboy** [comment]
Fix it by importing:

```
implementation("org.javamoney:moneta:1.1")
```

**Comment by slaviboy** [comment]
@keilw Will it be possible to make, latest version 1.4.2 supported by Android Studio projects?

**Comment by keilw** [comment]
@slaviboy 1.1 is quite old, 
I cannot promise any changes to the properties, because one aspect is overloading them in sub-modules.

**Comment by keilw** [comment]
@slaviboy You should be able to do this by excluding certain artifacts in Gradle:
https://discuss.gradle.org/t/how-can-i-declare-an-exclusion-on-my-source-folder/22821/4
or
https://stackoverflow.com/questions/53394850/exclude-file-from-jar-using-gradle
