### ISSUE TITLE
Problem when upgrade 1.4.2 to 1.4.3

### ISSUE THREAD

**Issue by MehrunesSky** [JavaMoney/jsr354-ri#403]
Hello, 

When i upgrade my project from 1.4.2 to 1.4.3, my project cannot start because tomcat cannot find the javax.annotation.PostConstruct.

Do you have any information about this problem? 

Could this be related to the fact that in moneta-core's module-info.java, the "requires java.annotation" has been replaced by "requires jakarta.annotation;"? 

PS : I am on Java 17

**Comment by keilw** [comment]
@MehrunesSky Did using Tomcat 10 solve your problem?

**Comment by keilw** [comment]
I assume, this can be addressed by using Tomcat 10 or a similar (Jakarta EE 9 compatible) environment, or as an alternative explicitly adding the correct Jakarta Annotations version.
