### ISSUE TITLE
Hard dependency on okhttp, osgi?

### ISSUE THREAD

**Issue by hrstoyanov** [JavaMoney/jsr354-ri#404]
If  read the POM correctly moneta-core has hard  (compile) dependency on okhttp? What is the reason for a this (java has its own Java http client API since Java 11). Also not sure why are Jakarta Annotations also used? Some OSGI?

**Comment by keilw** [comment]
Because Moneta is still backward-compatible with Java 8. Maybe 1.5.x could raise the bar to Java 11, but for now it's still Java 8.

**Comment by hrstoyanov** [comment]
Ok, I see the reasoning... But if you want this library to be truly versatile and non-intrusive, please  consider removing Jakarta EE requirements (so it is useful in Micronaut, Helidon SE, Spring) and prefer core Java SE over external libraries.

**Comment by keilw** [comment]
It's a standard library that was refactored from `javax` (just like JavaMoney) to `jakarta`, but it's a single standalone library, used by pretty much all the mentioned frameworks anyway (https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api)

**Comment by dstoch** [comment]
While the dependency on jakarta.annotation-api is not very problematic, the dependency on okhttp is (these libraries do not have versions as OSGi bundles). Why the need to introduce this dependency from version 1.4.3, it was not there before?
Is it necessary to work always, or only for certain selected functions of moneta-core and could it be optional (Import-package optional)?

I cannot reopen this issue, should I create a new one for this problem?
